platform :ios, "10.0"
use_frameworks! :linkage => :static

source "https://github.com/CocoaPods/Specs.git"

def pod_Common
  pod "JSSkeleton", :path => ".."
  pod "QMUIKit"
  pod "Masonry"
end

target "JSSkeletonExample" do
  pod_Common
  pod "LookinServer", "~> 1.0.4", :configurations => ["Debug"]
  pod "MLeaksFinder", :configurations => ["Debug"]
  pod "FBRetainCycleDetector", :git => "https://github.com/jiasongs/FBRetainCycleDetector.git", :configurations => ["Debug"]
end

target "JSSkeletonExampleMacOS" do
  pod_Common
end

# https://github.com/CocoaPods/CocoaPods/issues/8891
def fix_resource_bundle_signing(installer)
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        if config.build_settings["DEVELOPMENT_TEAM"].nil?
          config.build_settings["DEVELOPMENT_TEAM"] = "KJ6AEY5JEH"
        end
        if config.build_settings["CODE_SIGN_IDENTITY[sdk=macosx*]"].nil?
          config.build_settings["CODE_SIGN_IDENTITY[sdk=macosx*]"] = "-"
        end
      end
    end
  end
end

post_install do |installer|
  fix_resource_bundle_signing(installer)
end

